version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pkl_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pkl_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: pkl_backend_container
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      DB_DATABASE: pkl_db
      DB_DIALECT: mysql
      PORT: 5000

  frontend:
    build:
      context: ./sidemi
      args:
        # PENTING: Ganti URL ini dengan IP/Domain server jika dideploy ke production
        # Contoh: http://api.domainanda.com
        NEXT_PUBLIC_API_URL: http://localhost:5000
    container_name: pkl_frontend_container
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
